

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: 
    jobs:
      - job: "SonarCloud"
        steps:
        - task: SonarCloudPrepare@1
          inputs:
            SonarCloud: 'AzureDevOpsSonarCloud'
            organization: 'asrailuna'
            scannerMode: 'MSBuild'
            projectKey: 'asrailuna'
            projectName: 'Project0Azure'
        - task: SonarCloudAnalyze@1
