

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: 
    jobs:
      - job: "SonarCloud"
        steps:
        - script: dotnet build 'Project0/Project 0/Project 0.sln'
        - task: SonarCloudPrepare@1
          inputs:
            SonarCloud: 'AzureDevOpsSonarCloud'
            organization: 'asrailuna'
            scannerMode: 'MSBuild'
            projectKey: 'AsraiLuna_Project0Azure'
            projectName: 'Project0Azure'
            projectVersion: '1.0'
        - task: UseDotNet@2
          inputs:
            packageType: sdk
            version: 2.1.806
        - script: dotnet build 'Project0/Project 0/Project 0.sln'
        - task: SonarCloudAnalyze@1
